nshlib:support nsh can redirect
apache/incubator-nuttx-apps pull request #1224
Opened 2022-07-21 08:45 UTC by anjiahao1

Signed-off-by: anjiahao <anjiahao@xiaomi.com>

## Summary
if rcS use set +x or other，rcS can output other path
## Impact
nothing
## Testing
CI

2022-07-21 08:50 UTC, pkarashchenko commented on nshlib/nsh_script.c
> +#include <fcntl.h>
please move this above `#include "nsh.h"`

2022-07-21 08:50 UTC, pkarashchenko commented on nshlib/nsh_script.c
> +  if (fd >= 0)
let's use the same condition here and at line 49

2022-07-21 09:23 UTC, davids5 requested changes
typo?

2022-07-21 09:23 UTC, davids5 commented on nshlib/Kconfig
> +config NSH_SCRIRT_REDIRECT_PATH
```suggestion
config NSH_SCRIRT_REDIRECT_PATH
```
```suggestion
config NSH_SCRIPT_REDIRECT_PATH
```

???

2022-07-21 09:34 UTC, anjiahao1 commented on nshlib/Kconfig
> +config NSH_SCRIRT_REDIRECT_PATH
sorry

2022-07-21 12:42 UTC, pkarashchenko commented
Please fix style issues

2022-07-21 12:58 UTC, pkarashchenko commented on nshlib/nsh_script.c
> +      if (fd >= 0)
can `fd` check be unified here and at line 49 above?

2022-07-22 05:28 UTC, pkarashchenko approved these changes

2022-07-22 05:52 UTC, merged